import { ClubMembersTable, type ClubMembersLabels } from "@/components/admin/ClubMembersTable";
import { Disclosure, JsonForm } from "@/components/admin/JsonForm";
import { SectionHeading } from "@/components/ui";
import { PLAYER_POSITIONS, STAFF_ROLES, type ClubMemberPosition } from "@/lib/clubMembers";
import type { ClubMemberRole } from "@/server/repositories/types";
import type { MyClubApprovedPageData } from "@/server/services/myClub";

export function MyClubMembers({ data, labels, clubLabels, memberLabels }: { data: MyClubApprovedPageData; labels: Record<string, string>; clubLabels: Record<string, string>; memberLabels: ClubMembersLabels }) {
  const addMemberFields = (defaultRole: ClubMemberRole) => [{ name: "fullName", label: memberLabels.fullName, required: true as const }, { name: "memberRole", label: memberLabels.role, type: "select" as const, required: true as const, defaultValue: defaultRole, options: [{ value: "player", label: memberLabels.roleLabels.player }, { value: "coach", label: memberLabels.roleLabels.coach }, { value: "staff", label: memberLabels.roleLabels.staff }] }, { name: "shirtNumber", label: memberLabels.number, type: "number" as const, min: 0, max: 99 }, { name: "position", label: memberLabels.position, type: "select" as const, options: (defaultRole === "player" ? PLAYER_POSITIONS : STAFF_ROLES.filter((role) => role !== "HEAD_COACH")).map((value) => ({ value, label: memberLabels.positionLabels[value as ClubMemberPosition] })) }, { name: "birthYear", label: memberLabels.born, type: "number" as const, min: 1900, max: 2200 }];
  return <><section aria-labelledby="my-club-roster"><SectionHeading id="my-club-roster" action={<span className="text-[length:var(--text-sm)] font-semibold text-muted">{data.players.length}</span>}>{clubLabels.roster}</SectionHeading><div className="flex flex-col gap-4"><ClubMembersTable actionBase="/api/owner/club/members" members={data.players} emptyLabel={clubLabels.noRoster} labels={memberLabels} /><Disclosure label={labels.addAthlete}><JsonForm action="/api/owner/club/members" submitLabel={labels.tableSave} compact fields={addMemberFields("player")} /></Disclosure></div></section>
  <section aria-labelledby="my-club-staff"><SectionHeading id="my-club-staff" action={<span className="text-[length:var(--text-sm)] font-semibold text-muted">{data.coachStaff.length}</span>}>{clubLabels.coachingStaff}</SectionHeading><div className="flex flex-col gap-4"><ClubMembersTable actionBase="/api/owner/club/members" members={data.coachStaff} emptyLabel={clubLabels.noCoachingStaff} labels={memberLabels} /><Disclosure label={labels.addStaff}><JsonForm action="/api/owner/club/members" submitLabel={labels.tableSave} compact fields={addMemberFields("coach")} /></Disclosure></div></section></>;
}
