import Link from "next/link";
import { Disclosure, JsonForm } from "@/components/admin/JsonForm";
import { Badge, SectionHeading } from "@/components/ui";
import { SOCIAL_LINK_FIELDS } from "@/lib/clubSocialLinks";
import type { MyClubApprovedPageData } from "@/server/services/myClub";

export function MyClubDetails({ data, labels, clubLabels }: { data: MyClubApprovedPageData; labels: Record<string, string>; clubLabels: Record<string, string> }) {
  const { club, achievements, socials, documents } = data;
  return <><section aria-labelledby="my-club-info"><SectionHeading id="my-club-info">{labels.clubInformation}</SectionHeading><Disclosure label={labels.editClub}><JsonForm action="/api/owner/club" method="PATCH" submitLabel={labels.saveChanges} fields={[
    { name: "name", label: labels.fieldName, required: true, defaultValue: club.name }, { name: "province", label: labels.fieldProvince, required: true, defaultValue: club.province },
    { name: "foundingYear", label: labels.fieldFoundingYear, type: "number", min: 1800, max: 2200, defaultValue: club.founding_year }, { name: "logoUrl", label: labels.fieldLogoUrl, type: "url", defaultValue: club.logo_url },
    { name: "websiteUrl", label: labels.fieldWebsite, type: "url", defaultValue: club.website_url }, { name: "contactEmail", label: labels.fieldContactEmail, type: "email", defaultValue: club.contact_email }, { name: "contactPhone", label: labels.fieldContactPhone, type: "tel", defaultValue: club.contact_phone },
    { name: "socialLinks", label: labels.fieldSocialLinks, type: "urlgroup", keys: SOCIAL_LINK_FIELDS, colSpan: 2, defaultValue: club.social_links },
  ]} /></Disclosure></section>
  <section aria-labelledby="my-club-achievements"><SectionHeading id="my-club-achievements">{clubLabels.achievements}</SectionHeading>{achievements ? <div className="rounded-[var(--radius-lg)] border border-border/80 bg-surface p-6 shadow-[var(--shadow-xs)]"><p className="max-w-[68ch] whitespace-pre-line text-[length:var(--text-base)] leading-relaxed">{achievements}</p></div> : <p className="text-[length:var(--text-sm)] text-muted">{clubLabels.noAchievements}</p>}</section>
  <section aria-labelledby="my-club-contact"><SectionHeading id="my-club-contact">{clubLabels.contactSocial}</SectionHeading><div className="grid gap-6 lg:grid-cols-2"><div className="min-w-0 rounded-[var(--radius-lg)] border border-border/80 bg-surface p-6 shadow-[var(--shadow-xs)]"><h3 className="eyebrow mb-3 text-muted">{clubLabels.contactInfo}</h3>{club.contact_email || club.contact_phone || club.website_url ? <dl className="flex flex-col gap-2.5 text-sm">{club.contact_email && <div className="flex items-center gap-2"><span className="text-muted">Email:</span><a href={`mailto:${club.contact_email}`} className="break-all font-semibold hover:underline">{club.contact_email}</a></div>}{club.contact_phone && <div className="flex items-center gap-2"><span className="text-muted">{clubLabels.phone}:</span><span className="font-semibold">{club.contact_phone}</span></div>}{club.website_url && <div className="flex items-center gap-2"><span className="text-muted">{clubLabels.website}:</span><a href={club.website_url} target="_blank" rel="noopener noreferrer" className="break-all font-semibold text-brand-text-text hover:underline">{club.website_url}</a></div>}</dl> : <p className="text-[length:var(--text-sm)] text-muted">{clubLabels.noContact}</p>}</div><div className="min-w-0 rounded-[var(--radius-lg)] border border-border/80 bg-surface p-6 shadow-[var(--shadow-xs)]"><h3 className="eyebrow mb-3 text-muted">{clubLabels.social}</h3>{socials.length > 0 ? <div className="flex flex-wrap gap-2.5">{socials.map(([key, url]) => <a key={key} href={url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 rounded-[var(--radius-md)] border border-border-strong/80 bg-surface-sunken/60 px-3 py-1.5 text-sm font-semibold capitalize hover:border-foreground/40 hover:bg-surface"><span>{key}</span><span aria-hidden="true" className="text-muted text-xs">↗</span></a>)}</div> : <p className="text-[length:var(--text-sm)] text-muted">{clubLabels.noSocial}</p>}</div></div></section>
  <section aria-labelledby="my-club-documents"><SectionHeading id="my-club-documents">{clubLabels.documents}</SectionHeading>{documents.length > 0 ? <ul className="divide-y divide-border overflow-hidden rounded-[var(--radius-lg)] border border-border bg-surface shadow-[var(--shadow-xs)]">{documents.map((doc) => <li key={doc.id} className="flex flex-wrap items-center justify-between gap-3 p-4 sm:px-6"><div className="flex items-center gap-2.5"><span className="text-sm font-semibold">{doc.filename}</span><Badge tone={doc.is_public ? "success" : "muted"}>{doc.is_public ? labels.documentPublic : labels.documentPrivate}</Badge></div><Link href={`/api/owner/club/documents/${doc.id}`} className="text-sm font-semibold text-brand-text-text hover:underline">{clubLabels.viewDocument}</Link></li>)}</ul> : <p className="text-[length:var(--text-sm)] text-muted">{clubLabels.noDocuments}</p>}</section></>;
}
