import "server-only";
import { queryOne, transaction } from "@/server/db/pool";
import type { Club } from "../types";
import { CLUB_COLUMNS, type ClubInput } from "./shared";

export function requestClubDeletion(clubId: number, ownerId: number): Promise<{ club_id: number } | null> { return queryOne(`INSERT INTO club_deletion_requests (club_id, requested_by) SELECT id, owner_id FROM clubs WHERE id = $1 AND owner_id = $2 ON CONFLICT (club_id) DO NOTHING RETURNING club_id`, [clubId, ownerId]); }
export function cancelClubDeletionRequest(clubId: number, ownerId: number): Promise<{ club_id: number } | null> { return queryOne(`DELETE FROM club_deletion_requests WHERE club_id = $1 AND requested_by = $2 RETURNING club_id`, [clubId, ownerId]); }
export async function deleteRequestedClub(clubId: number): Promise<boolean> { return transaction(async (client) => (await client.query(`DELETE FROM clubs WHERE id = $1 AND EXISTS (SELECT 1 FROM club_deletion_requests WHERE club_id = clubs.id)`, [clubId])).rowCount === 1); }
export function createClub(input: ClubInput): Promise<Club | null> { return queryOne<Club>(`INSERT INTO clubs (slug, name, province, founding_year, logo_url, achievements_en, achievements_vi, contact_email, contact_phone, website_url, social_links, is_approved, approved_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12, CASE WHEN $12 THEN now() ELSE NULL END) RETURNING ${CLUB_COLUMNS}`, [input.slug, input.name, input.province, input.foundingYear, input.logoUrl, input.achievementsEn, input.achievementsVi, input.contactEmail, input.contactPhone, input.websiteUrl, JSON.stringify(input.socialLinks), input.isApproved]); }
export function updateClub(id: number, input: ClubInput): Promise<Club | null> { return queryOne<Club>(`UPDATE clubs SET slug=$2, name=$3, province=$4, founding_year=$5, logo_url=$6, achievements_en=$7, achievements_vi=$8, contact_email=$9, contact_phone=$10, website_url=$11, social_links=$12, is_approved=$13, approved_at = CASE WHEN $13 AND approved_at IS NULL THEN now() WHEN NOT $13 THEN NULL ELSE approved_at END WHERE id=$1 RETURNING ${CLUB_COLUMNS}`, [id, input.slug, input.name, input.province, input.foundingYear, input.logoUrl, input.achievementsEn, input.achievementsVi, input.contactEmail, input.contactPhone, input.websiteUrl, JSON.stringify(input.socialLinks), input.isApproved]); }
export function setClubApproval(id: number, isApproved: boolean): Promise<Club | null> { return queryOne<Club>(`UPDATE clubs SET is_approved = $2, approved_at = CASE WHEN $2 THEN COALESCE(approved_at, now()) ELSE NULL END WHERE id = $1 RETURNING ${CLUB_COLUMNS}`, [id, isApproved]); }
