import { requireRole } from "@/server/auth/guard";
import {
  createAndAssignClubOwner,
  unassignClubOwner,
} from "@/server/repositories/clubOwners";
import { hashPassword } from "@/server/auth/password";
import { fail, notFound, ok, parseId } from "@/server/api/respond";
import { Validator, readJson } from "@/server/validation/validate";
import { auditedAdminMutation } from "@/server/security/adminAudit";

/**
 * Admin creates and assigns a Club Owner account for one club — the
 * "ASSIGN / CREATE CLUB OWNER" step. Gated `requireRole()` (admin/superadmin),
 * the same level as BR-001 approval and the document-publish toggle: deciding
 * who can act as a club is that class of decision.
 *
 * The new account's id is generated by the database inside this request and
 * used immediately — nothing here ever trusts a client-supplied owner id or
 * club id pairing as proof of anything.
 */
export async function POST(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const guard = await requireRole();
  if (!guard.ok) return guard.response;

  const id = parseId((await params).id);
  if (!id) return notFound();

  try {
    const body = await readJson(request);
    const v = new Validator(body);
    v.only(["email", "password"]);
    const email = v.email("email", { required: true }) ?? "";
    // Same 10-char minimum as staff accounts (see /api/admin/users).
    const password = v.string("password", { required: true, min: 10, max: 200 }) ?? "";
    v.assert();

    const passwordHash = await hashPassword(password);
    const result = await auditedAdminMutation(
      request,
      (assigned) => ({ actorId: guard.admin.id, action: "club.owner.assign", resourceType: "club", resourceId: id, metadata: assigned.ok ? { ownerId: assigned.owner.id } : undefined }),
      () => createAndAssignClubOwner(id, { email, passwordHash }),
      (assigned) => assigned.ok
    );

    if (!result.ok) {
      if (result.reason === "clubNotFound") return notFound();
      // clubAlreadyOwned / emailTaken — both a conflict with existing state.
      return Response.json({ error: result.reason }, { status: 409 });
    }
    return ok({ owner: result.owner }, 201);
  } catch (error) {
    return fail("assign club owner", error);
  }
}

/** Unassigns the club's current owner (the account itself is deactivated, not deleted). */
export async function DELETE(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const guard = await requireRole();
  if (!guard.ok) return guard.response;

  const id = parseId((await params).id);
  if (!id) return notFound();

  try {
    const result = await auditedAdminMutation(
      request,
      { actorId: guard.admin.id, action: "club.owner.remove", resourceType: "club", resourceId: id },
      () => unassignClubOwner(id),
      (removed) => removed.ok
    );
    if (!result.ok) return notFound();
    return ok({ club: result.club });
  } catch (error) {
    return fail("unassign club owner", error);
  }
}
