import { LocalizedPairFields, LocalizedSingleFields } from "./LocalizedFields";
import type { FieldSpec } from "./fieldSpec";
import { Field, controlClass, controlInvalidClass, textareaClass } from "@/components/ui";

export function JsonFormFields({ fields, fieldId, errors, errorForCode, compact, translationResetVersion, urlPlaceholder }: { fields: readonly FieldSpec[]; fieldId: (name: string) => string; errors: Record<string, string>; errorForCode: (code: string) => string; compact: boolean; translationResetVersion: number; urlPlaceholder: string }) {
  return <>{fields.map((field) => {
    if (field.type === "localizedPair") return <LocalizedPairFields key={`${field.en.name}-${field.vi.name}-${field.en.defaultValue ?? ""}-${field.vi.defaultValue ?? ""}-${translationResetVersion}`} pair={field} fieldId={fieldId} errors={errors} errorForCode={errorForCode} />;
    if (field.type === "localizedSingle") return <LocalizedSingleFields key={`${field.enName}-${field.viName}-${field.defaultEn ?? ""}-${field.defaultVi ?? ""}-${translationResetVersion}`} field={field} fieldId={fieldId} errors={errors} errorForCode={errorForCode} />;
    const message = errors[field.name] ? errorForCode(errors[field.name]) : null;
    const invalid = message ? controlInvalidClass : "";
    if (field.type === "checkbox") return <label key={field.name} className={`flex cursor-pointer items-center gap-2.5 text-[length:var(--text-sm)] font-semibold ${field.colSpan === 2 ? "sm:col-span-2" : ""}`}><input type="checkbox" id={fieldId(field.name)} name={field.name} defaultChecked={field.defaultChecked} className="h-4 w-4 rounded-[2px] border-border-strong accent-[var(--brand)]" />{field.label}{field.hint && <span className="text-[length:var(--text-xs)] font-normal text-muted">{field.hint}</span>}</label>;
    if (field.type === "urlgroup") return <div key={field.name} className={`flex flex-col gap-3 ${field.colSpan === 2 ? "sm:col-span-2" : ""}`}><span className="text-[length:var(--text-sm)] font-semibold">{field.label}{field.hint && <span className="ml-2 text-[length:var(--text-xs)] font-normal text-muted">{field.hint}</span>}</span><div className="grid gap-3 sm:grid-cols-2">{field.keys.map(({ key, label }) => <Field key={key} id={fieldId(`${field.name}.${key}`)} label={label}>{(props) => <input {...props} name={`${field.name}.${key}`} type="url" defaultValue={field.defaultValue?.[key] ?? ""} placeholder={urlPlaceholder} className={controlClass} />}</Field>)}</div></div>;
    return <Field key={field.name} id={fieldId(field.name)} label={field.label} required={"required" in field ? field.required : false} hint={field.hint} error={message} className={[field.colSpan === 2 ? "sm:col-span-2" : "", compact ? "min-w-40 flex-1" : ""].join(" ")}>{(props) => field.type === "textarea" ? <textarea {...props} name={field.name} rows={field.rows ?? 3} defaultValue={field.defaultValue ?? ""} className={`${textareaClass} ${invalid}`} /> : field.type === "select" ? <select {...props} name={field.name} defaultValue={field.defaultValue ?? ""} className={`${controlClass} ${invalid}`}>{!field.required && <option value="">—</option>}{field.options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select> : <input {...props} name={field.name} type={field.type ?? "text"} defaultValue={field.defaultValue ?? ""} min={field.min} max={field.max} className={`${controlClass} ${invalid}`} />}</Field>;
  })}</>;
}
