/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  roleEn?: string;
  roleVi?: string;
  role?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  officeName?: string;
  address?: string;
  hotline?: string;
  emails?: Array<{
    label?: string;
    address?: string;
    _type: "supportEmail";
    _key: string;
  }>;
  officeHours?: string;
  note?: BlockContent;
  formIntro?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type PartnerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "partner";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  brandStory?: BlockContent;
  vision?: string;
  mission?: string;
  tournamentSystem?: BlockContent;
  organizerAndPartners?: BlockContent;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  partners?: Array<
    {
      _key: string;
    } & PartnerReference
  >;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  heroSlides?: Array<{
    headline?: string;
    subheadline?: string;
    videoUrl?: string;
    poster?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    ctaLabel?: string;
    ctaHref?: string;
    _type: "heroSlide";
    _key: string;
  }>;
  tagline?: string;
  missionTitle?: string;
  missionOverview?: BlockContent;
  championsCorner?: {
    clubName?: string;
    seasonLabel?: string;
    summary?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    clubSlug?: string;
  };
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type NewsArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "newsArticle";
};

export type GalleryItemReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "galleryItem";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: NewsArticleReference | GalleryItemReference;
  language?: string;
};

export type GalleryItem = {
  _id: string;
  _type: "galleryItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  category?: "hall-of-glory" | "mvp-spotlight" | "behind-the-scenes";
  title?: string;
  photos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  body?: BlockContent;
};

export type NewsArticle = {
  _id: string;
  _type: "newsArticle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  category?:
    "tournament-news" | "inspirational-stories" | "knowledge-nutrition";
  date?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Partner
  | SanityImageCrop
  | SanityImageHotspot
  | ContactPage
  | BlockContent
  | PartnerReference
  | AboutPage
  | HomePage
  | TranslationMetadata
  | InternationalizedArrayReference
  | NewsArticleReference
  | GalleryItemReference
  | InternationalizedArrayReferenceValue
  | GalleryItem
  | NewsArticle
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: NEWS_LIST_QUERY
// Query: *[_type == "newsArticle" && language == $language && defined(slug.current)] | order(date desc){ _id, title, slug, category, date, coverImage }
export type NEWS_LIST_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  category:
    "inspirational-stories" | "knowledge-nutrition" | "tournament-news" | null;
  date: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: NEWS_ARTICLE_QUERY
// Query: *[_type == "newsArticle" && language == $language && slug.current == $slug][0]{ _id, title, category, date, coverImage, body }
export type NEWS_ARTICLE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  category:
    "inspirational-stories" | "knowledge-nutrition" | "tournament-news" | null;
  date: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  body: BlockContent | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage" && language == $language][0]{    brandStory,    vision,    mission,    tournamentSystem,    organizerAndPartners,    images,    partners[]-> {      _id,      name,      "role": coalesce(select($language == "vi" => roleVi), roleEn, role),      logo    }  }
export type ABOUT_PAGE_QUERY_RESULT = {
  brandStory: BlockContent | null;
  vision: string | null;
  mission: string | null;
  tournamentSystem: BlockContent | null;
  organizerAndPartners: BlockContent | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  partners: Array<{
    _id: string;
    name: string | null;
    role: string | null;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }> | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: GALLERY_ITEMS_QUERY
// Query: *[_type == "galleryItem" && language == $language] | order(_createdAt desc){ _id, category, title, photos, body }
export type GALLERY_ITEMS_QUERY_RESULT = Array<{
  _id: string;
  category: "behind-the-scenes" | "hall-of-glory" | "mvp-spotlight" | null;
  title: string | null;
  photos: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  body: BlockContent | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && language == $language][0]{    tagline,    missionTitle,    missionOverview,    heroSlides[]{      _key,      headline,      subheadline,      videoUrl,      poster,      ctaLabel,      ctaHref    },    championsCorner{      clubName,      seasonLabel,      summary,      image,      clubSlug    }  }
export type HOME_PAGE_QUERY_RESULT = {
  tagline: string | null;
  missionTitle: string | null;
  missionOverview: BlockContent | null;
  heroSlides: Array<{
    _key: string;
    headline: string | null;
    subheadline: string | null;
    videoUrl: string | null;
    poster: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    ctaLabel: string | null;
    ctaHref: string | null;
  }> | null;
  championsCorner: {
    clubName: string | null;
    seasonLabel: string | null;
    summary: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    clubSlug: string | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: HOME_NEWS_QUERY
// Query: *[_type == "newsArticle" && language == $language && defined(slug.current)]    | order(date desc)[0...5]{ _id, title, slug, category, date, coverImage }
export type HOME_NEWS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  category:
    "inspirational-stories" | "knowledge-nutrition" | "tournament-news" | null;
  date: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: HOME_HIGHLIGHTS_QUERY
// Query: *[_type == "galleryItem" && language == $language && count(photos) > 0]    | order(_createdAt desc)[0...6]{ _id, title, category, "photo": photos[0] }
export type HOME_HIGHLIGHTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  category: "behind-the-scenes" | "hall-of-glory" | "mvp-spotlight" | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage" && language == $language][0]{    officeName,    address,    hotline,    emails[]{ label, address },    officeHours,    note,    formIntro  }
export type CONTACT_PAGE_QUERY_RESULT = {
  officeName: string | null;
  address: string | null;
  hotline: string | null;
  emails: Array<{
    label: string | null;
    address: string | null;
  }> | null;
  officeHours: string | null;
  note: BlockContent | null;
  formIntro: string | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: NEWS_RELATED_QUERY
// Query: *[_type == "newsArticle" && language == $language && defined(slug.current)      && slug.current != $slug]    | order(date desc)[0...3]{ _id, title, slug, category, date, coverImage }
export type NEWS_RELATED_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  category:
    "inspirational-stories" | "knowledge-nutrition" | "tournament-news" | null;
  date: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: NEWS_SITEMAP_QUERY
// Query: *[_type == "newsArticle" && defined(slug.current)]{    "slug": slug.current,    "updatedAt": _updatedAt  }
export type NEWS_SITEMAP_QUERY_RESULT = Array<{
  slug: string | null;
  updatedAt: string;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: NEWS_TRANSLATIONS_QUERY
// Query: *[_type == "translation.metadata" &&      references(*[_type == "newsArticle" && slug.current == $slug][0]._id)][0]    .translations[]{ "language": value->language, "slug": value->slug.current }
export type NEWS_TRANSLATIONS_QUERY_RESULT = Array<{
  language: string | null;
  slug: string | null;
}> | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "newsArticle" && language == $language && defined(slug.current)] | order(date desc){ _id, title, slug, category, date, coverImage }': NEWS_LIST_QUERY_RESULT;
    '*[_type == "newsArticle" && language == $language && slug.current == $slug][0]{ _id, title, category, date, coverImage, body }': NEWS_ARTICLE_QUERY_RESULT;
    '*[_type == "aboutPage" && language == $language][0]{\n    brandStory,\n    vision,\n    mission,\n    tournamentSystem,\n    organizerAndPartners,\n    images,\n    partners[]-> {\n      _id,\n      name,\n      "role": coalesce(select($language == "vi" => roleVi), roleEn, role),\n      logo\n    }\n  }': ABOUT_PAGE_QUERY_RESULT;
    '*[_type == "galleryItem" && language == $language] | order(_createdAt desc){ _id, category, title, photos, body }': GALLERY_ITEMS_QUERY_RESULT;
    '*[_type == "homePage" && language == $language][0]{\n    tagline,\n    missionTitle,\n    missionOverview,\n    heroSlides[]{\n      _key,\n      headline,\n      subheadline,\n      videoUrl,\n      poster,\n      ctaLabel,\n      ctaHref\n    },\n    championsCorner{\n      clubName,\n      seasonLabel,\n      summary,\n      image,\n      clubSlug\n    }\n  }': HOME_PAGE_QUERY_RESULT;
    '*[_type == "newsArticle" && language == $language && defined(slug.current)]\n    | order(date desc)[0...5]{ _id, title, slug, category, date, coverImage }': HOME_NEWS_QUERY_RESULT;
    '*[_type == "galleryItem" && language == $language && count(photos) > 0]\n    | order(_createdAt desc)[0...6]{ _id, title, category, "photo": photos[0] }': HOME_HIGHLIGHTS_QUERY_RESULT;
    '*[_type == "contactPage" && language == $language][0]{\n    officeName,\n    address,\n    hotline,\n    emails[]{ label, address },\n    officeHours,\n    note,\n    formIntro\n  }': CONTACT_PAGE_QUERY_RESULT;
    '*[_type == "newsArticle" && language == $language && defined(slug.current)\n      && slug.current != $slug]\n    | order(date desc)[0...3]{ _id, title, slug, category, date, coverImage }': NEWS_RELATED_QUERY_RESULT;
    '*[_type == "newsArticle" && defined(slug.current)]{\n    "slug": slug.current,\n    "updatedAt": _updatedAt\n  }': NEWS_SITEMAP_QUERY_RESULT;
    '*[_type == "translation.metadata" &&\n      references(*[_type == "newsArticle" && slug.current == $slug][0]._id)][0]\n    .translations[]{ "language": value->language, "slug": value->slug.current }': NEWS_TRANSLATIONS_QUERY_RESULT;
  }
}
